### ISSUE TITLE
Powershell error when config has no module_paths

### ISSUE THREAD

**Issue by dylanmei** [mefellows/vagrant-dsc#11]
Given this config, without a `module_paths` declared:

    config.vm.provision "dsc" do |dsc|
      dsc.manifests_path = "../dsc"
      dsc.configuration_file = "Site.ps1"
      dsc.configuration_params = {
        "-NodeName" => "localhost",
      }
    end

I get the error:

    Resolve-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
    At C:\tmp\vagrant-dsc-runner.ps1:10 char:83

Hacking the runner template gets me around the error.

    # Set the local PowerShell Module environment path
    <% if !options[:module_paths].empty?  %>
    ...
    <% end %>

**Comment by mefellows** [comment]
Thanks @dylanmei, looks like a sloppy error check in the template. I'll take a look at this today.

**Comment by dylanmei** [comment]
No troubs. Thanks for this plugin!

**Comment by mefellows** [comment]
OK, I believe PR #13 should fix this issue - when you get a chance do you mind verifying with the latest release (I have pushed v1.0.3 to RubyGems)?

**Comment by dylanmei** [comment]
Works like a charm. Thanks!

**Comment by mefellows** [comment]
Great - thanks!
