### ISSUE TITLE
The term '\tmp\vagrant-dsc-1\Site.ps1' is not recognized...

### ISSUE THREAD

**Issue by dylanmei** [mefellows/vagrant-dsc#12]
Given the following config:

    config.vm.provision "dsc" do |dsc|
      dsc.manifests_path = "../dsc"
      dsc.configuration_file = "Site.ps1"
      dsc.configuration_params = {
        "-NodeName" => "localhost",
      }
    end

I get this failure in the runner script.

    The term '\tmp\vagrant-dsc-4\Site.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.

Adding an explicit `temp_dir = "C:/tmp/dsc"` gets me around the error. There's no cygwin on my guest and my Vagrantfile has both of these windows-y settings:

    config.vm.guest = :windows
    config.communicator = :winrm

**Comment by mefellows** [comment]
OK, looks like there is a bug with relative paths that traverse the tree backwards (ironically similar to the other issue we've [seen](https://github.com/packer-community/winrmcp/issues/1) recently!).

Hopefully will wrap up a fix for this today/tonight. Good spot.

For the time being, a workaround would be to move the `dsc` folder to the same dir as the `Vagrantfile`.

Cheers,
Matt

**Comment by mefellows** [comment]
OK, I believe PR #13 should fix this issue - when you get a chance do you mind verifying with the latest release (I have pushed v1.0.3 to RubyGems)?

**Comment by dylanmei** [comment]
Works like a charm. Thanks!

**Comment by mefellows** [comment]
Great - thanks!
