### ISSUE TITLE
mfellows/win2012r2 v1.0.1 missing metadata.json

### ISSUE THREAD

**Issue by dragon788** [mefellows/vagrant-dsc#22]
Was trying to use your example box from the development Vagrantfile and get a 404 when trying to pull the box (because 1.0.0 is specified) and looking in the Atlas repo I see that 1.0.1 is the latest, but trying to pull it I get an error about metadata.json missing.

```The "metadata.json" file for the box 'mfellows/windows2012r2' was not found.```

**Comment by mefellows** [comment]
As per #23,  I _think_ I have the box (or at least one of them) on my work machine - i'll try to upload today. Something fishy going on!

**Comment by mefellows** [comment]
In the process of uploading a 1.0.1 box from home - this could take a while (thanks Windows). cc: #23

**Comment by mefellows** [comment]
Box has been uploaded (finally). I haven't pulled the thing all the way back down, but running `vagrant init mfellows/windows2012r2; vagrant up --provider virtualbox` starts the download process.

Let me know how you go, closing for now.

**Comment by dragon788** [comment]
@mefellows Still getting the error about a missing metadata.json. I'm grabbing the box "by hand" to pop it open and see if there is something about the internal structure that is missing or corrupted.

**Comment by dragon788** [comment]
Upon opening the 1.0.1 virtualbox.box file it internally is showing a version 1.0.0 and the metadata.json does exist in that folder. I wonder if the fact that the internal version and external versions don't match is what is causing the metadata.json error. Did you repackage the box using vagrant on your local machine and perhaps it didn't bump the version before you uploaded?

**Comment by dragon788** [comment]
It appears that the structure of this one is actually set up incorrectly. I compared to a Vagrant box built using Packer and it only has the Vagrantfile/metadata.json/*.vmdk/box.ovf in the .box file, where this one has it nested layers deep.

**Comment by dragon788** [comment]
Upon unpacking and repacking only the contents of the 'virtualbox' folder into the box file I was able to successfully add and up the box from my local Vagrant repository server.

**Comment by mefellows** [comment]
Oh my goodness, how silly of me! Re-opening so that I can upload a valid one. Thanks for following this up @dragon788.

**Comment by mefellows** [comment]
Just a side note here - have tried for the past 3 days straight uploading latest box to no avail. 4th time lucky (hint: `caffeinate -sim`)

**Comment by mefellows** [comment]
OK have pushed box back up after a `vagrant box repackage ...`.

**Comment by mefellows** [comment]
OK overnight I pulled the latest and it came down - closing!

**Comment by StefanSchoof** [comment]
I can now pull the 1.0.1 and `vagrant up`, but the example [Vagrantfile](https://github.com/mefellows/vagrant-dsc/blob/master/development/web/Vagrantfile#L20) still requires 1.0.0 of this box.

**Comment by mefellows** [comment]
Thanks Stefan - have updated that file.
