### ISSUE TITLE
mfellows/win2012r2 v1.0.0 missing box on Atlas

### ISSUE THREAD

**Issue by dragon788** [mefellows/vagrant-dsc#23]
Appears to have been externally hosted and Atlas can no longer resolve the box address.

**Comment by mefellows** [comment]
I think I have the box on my work machine - i'll try to upload today.

**Comment by mefellows** [comment]
Box has been uploaded (finally). I haven't pulled the thing all the way back down, but running `vagrant init mfellows/windows2012r2; vagrant up --provider virtualbox` starts the download process.

Let me know how you go, closing for now.

**Comment by dragon788** [comment]
The actual error I get when trying to download this version 1.0.0 "by hand" is that the Amazon bucket it was associated with no longer exists.

https://s3-ap-southeast-2.amazonaws.com/onegeekau/packer/windows2012r2.box

<Error>
<script/>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>onegeekau</BucketName>
<RequestId>76E3BE65047B08BB</RequestId>
<HostId>
L0mmy3P8Zds+yZYB4VTMBmVQG3UcTvyMm0GQrNd0kbuih6sWtThnTzXf/O/pL1qO4c8gwtK+pIo=
</HostId>
</Error>

**Comment by mefellows** [comment]
Yep I removed it in a cleanup a while ago. The 1.0.1 is the correct version (there were issues with that box). I'll see if I can remove/deprecate it.
