### ISSUE TITLE
xActiveDirectory module is not found correct in modules

### ISSUE THREAD

**Issue by StefanSchoof** [mefellows/vagrant-dsc#28]
I try to set a dc with vagrant-dsc using the xActiveDirectory DSC Module. I put the module in the modules Folder and when provision I get the error:
```
The PowerShell DSC resource xActiveDirectory does not exist at the PowerShell
module path nor is it registered as a WMI DSC resource.
```
Running 

```
> Get-DscResource

ImplementedAs   Name                      Module                         Properties
-------------   ----                      ------                         ----------
Binary          File                                                     {DestinationPath, Attributes, Checksum, C
PowerShell      Archive                   PSDesiredStateConfiguration    {Destination, Path, Checksum, Credential.
PowerShell      Environment               PSDesiredStateConfiguration    {Name, DependsOn, Ensure, Path...}
PowerShell      Group                     PSDesiredStateConfiguration    {GroupName, Credential, DependsOn, Descri
Binary          Log                       PSDesiredStateConfiguration    {Message, DependsOn}
PowerShell      Package                   PSDesiredStateConfiguration    {Name, Path, ProductId, Arguments...}
PowerShell      Registry                  PSDesiredStateConfiguration    {Key, ValueName, DependsOn, Ensure...}
PowerShell      Script                    PSDesiredStateConfiguration    {GetScript, SetScript, TestScript, Creden
PowerShell      Service                   PSDesiredStateConfiguration    {Name, BuiltInAccount, Credential, Depend
PowerShell      User                      PSDesiredStateConfiguration    {UserName, DependsOn, Description, Disabl
PowerShell      WindowsFeature            PSDesiredStateConfiguration    {Name, Credential, DependsOn, Ensure...}
PowerShell      WindowsProcess            PSDesiredStateConfiguration    {Arguments, Path, Credential, DependsOn..
PowerShell      xADComputer               xActiveDirectory               {ComputerName, DependsOn, Description, Di
PowerShell      xADDomain                 xActiveDirectory               {DomainAdministratorCredential, DomainNam
PowerShell      xADDomainController       xActiveDirectory               {DomainAdministratorCredential, DomainNam
PowerShell      xADDomainDefaultPasswo... xActiveDirectory               {DomainName, ComplexityEnabled, Credentia
PowerShell      xADDomainTrust            xActiveDirectory               {SourceDomainName, TargetDomainAdministra
PowerShell      xADGroup                  xActiveDirectory               {GroupName, Category, Credential, Depends
PowerShell      xADOrganizationalUnit     xActiveDirectory               {Name, Path, Credential, DependsOn...}
PowerShell      xADRecycleBin             xActiveDirectory               {EnterpriseAdministratorCredential, Fores
PowerShell      xADUser                   xActiveDirectory               {DomainName, UserName, CannotChangePasswo
PowerShell      xWaitForADDomain          xActiveDirectory               {DomainName, DependsOn, DomainUserCredent
```
found the xActiveDirectory module.

Copy the xActiveDirectory in the C:\Users\vagrant\Documents\WindowsPowerShell\Modules gives me the same error, but it works if I copy the module to C:\Users\vagrant\Documents\WindowsPowerShell\Modules

I created a minimal example at https://github.com/StefanSchoof/vagrant-dsc-xactivedirectory

(I am unsure if this is a vagrant-dsc, windows or box issue)

**Comment by mefellows** [comment]
Interesting. Have you tried running `vagrant provision` or `vagrant reload --provision` multiple times? I wonder if it's not picking it up the first time or something.

Also, I've had issues in the past with putting the upstream PoSH modules anywhere but the officially sanctioned paths (e.g. `C:\\Program Files\WindowsPowerShell\Modules`). Could you also please try popping the resource there?

**Comment by StefanSchoof** [comment]
Running multiple times and reboot does not change anything. Running the C:\tmp\vagrant-dsc-runner in the guest direct does also not help.

Copy it to the `C:\Program Files\WindowsPowerShell\Modules`  works (my curent workaround is `Copy-Item C:\\vagrant\\modules\\* -Destination 'C:\\Program Files\\WindowsPowerShell\\Modules' -Recurse -Force`)

This not the same error message, as when the modules is not in a path. Then I get the error: `Unable to load module 'xActiveDirectory': module not found.` I tried now other modules and I have the same behavior.

**Comment by mefellows** [comment]
Hmm that's no fun. Does the example project work for you?

**Comment by StefanSchoof** [comment]
The example project requires the version 1.0.0, which gets me the error `The requested URL returned error: 403 Forbidden`
When delete the version line, I run into https://github.com/mefellows/vagrant-dsc/issues/22.

**Comment by mefellows** [comment]
Ah yes, I need to get onto that. I'll try to fix that now (it will take a while to upload, sadly).

**Comment by mefellows** [comment]
FYI a new box has been published. I'm in the process of verifying it now (damn Windows boxes are uuuuugge).

**Comment by mefellows** [comment]
OK overnight I pulled the latest and it came down. When you get a chance @StefanSchoof could you please try with latest image?

**Comment by StefanSchoof** [comment]
Thanks, next week I have properly no time for this.

**Comment by StefanSchoof** [comment]
Using the `mfellows/windows2012r2` box does not change anything. For my purpose I will try to get #35 working and then I have this problem no longer. Should we close this issue?

**Comment by mefellows** [comment]
I think leave this open for now @StefanSchoof, we haven't gotten to the bottom of it yet. If #35 resolves it then great.

In the meanwhile, if modules are put in the right place on the guest machine, DSC _should_ work without the need for `Install-Module`. I think.

**Comment by mefellows** [comment]
Latest version `v1.1.0` released - let us know if all of your hard work has addressed this :)

**Comment by StefanSchoof** [comment]
Thanks. I can now set up a DC with the `v1.1.0`. I have to use the xActiveDirectory Version from https://github.com/PowerShell/xActiveDirectory/pull/101.

**Comment by mefellows** [comment]
Nice! Thanks for the PRs.
