### ISSUE TITLE
Enhancement: Install-Module support

### ISSUE THREAD

**Issue by StefanSchoof** [mefellows/vagrant-dsc#35]
With WMF5 there is support for the new [Install-Module](https://technet.microsoft.com/en-us/library/dn807162.aspx) allows installation of Modules. 

I think having a list of modules in the vagrant file, for which vagrant-dsc the installation of a module ensures would be great. 

In the Vargantfile I think something like:

```
dsc.module_install = ["xNetworking", "xSQLServer"]
```

I think of adding these modules to the generated runner.ps1 and write powershell code to test version and install if required.

Any thought about something like this?

**Comment by mefellows** [comment]
Love it! Actually I did something similar with the [Packer DSC plugin](https://github.com/mefellows/packer-dsc) - I just haven't had time/need to implement it - so please have at it ;)
