### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by reznet** [mefellows/vagrant-dsc#38]
I'm trying to build the plugin, but get an error from bundler.  I'm attempting to build on mac in order to get the fix from PR 37

je185066@WUSJE185066-13F ~/repos/vagrant-dsc$ bundle install
Your Gemfile lists the gem vagrant-dsc (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that vagrant-dsc (>= 0) should come from source at `.` and source at `.`
. Bundler cannot continue.

 #  from /Users/je185066/repos/vagrant-dsc/Gemfile:11
 #  -------------------------------------------
 #  group :plugins do
 >    gem "vagrant-dsc", path: "."
 #  end
 #  -------------------------------------------

**Comment by mefellows** [comment]
Hi @reznet, apologies I haven't pushed out a new Gem for #37 yet (lost my home internet until mid next week it seems). I'll see what I can do about alternatives.

In the meanwhile, can you please share your bundle and ruby versions for me?

**Comment by reznet** [comment]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Bundler version 1.13.2

**Comment by reznet** [comment]
Hi @mefellows Any update on either a new release or the bundler error?

**Comment by mefellows** [comment]
Hi Jeff, i haven't had a chance to fix this but i can repro. I'm without
Internet at home at the moment but in the meanwhile you're welcome to
submit a PR. I'd say it's just a dependency cleanup required.

**Comment by mefellows** [comment]
OK had a look at this tonight. In short, bundler 1.12.5 is the version you need - this is due to a hard dependency in Vagrant.

I'll update the docs, but essentially you can run `bundle _1.12.5_ <command>` and things work as you'd expect.

I've updated the `.appveyor.yml` which sorts out #41 in the process.

**Comment by reznet** [comment]
thanks for deploying a new release.  verified it fixed the powershell bug i was hitting.  :)

**Comment by mefellows** [comment]
Nice!
