### ISSUE TITLE
Better output format from WinRM shell

### ISSUE THREAD

**Issue by mefellows** [mefellows/vagrant-dsc#7]
WinRM communicator appears to send output back periodically to Vagrant in an ugly XML format. Make this nicer so output back to the user is sensible.

**Comment by Jonne** [comment]
Can we do something like this? http://msdn.microsoft.com/en-us/library/aa384351%28v=vs.85%29.aspx

**Comment by mefellows** [comment]
Possibly, from memory it was difficult to get access to the XML due to the way it was being slurped by the WinRM communicator. I'll investigate (it does bug me!).

**Comment by mefellows** [comment]
Commit fd01df558738935d402e5f8c198695f62887744b fixes this. New version v1.0.5 of gem released.
